### PR TITLE
Made commands non-case sensitive and made RPS code better.

### PR DESCRIPTION
**Pull request by MonliH**
I made the commands non-case sensitive, and made the RPS code more readable, consise, and clear.I also added the RPS command to the help command.

### CODE REVIEW

**Comment by thewilloftheshadow** [comment]
For `command.toLowercase`, the code already does this when it defines command: `const command = args.shift().toLowerCase()`

**Comment by MonliH** [comment]
It is? Ok, I'll fix that.

**Comment by thewilloftheshadow** [comment]
@MonliH i had to revert this, can you make a new pull request and do it again? some files on the host were corrupted

**Comment by MonliH** [comment]
Oof, ok I'll make another PR

**Pull request merged**
